terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  ligatures: false
  frontend: xterm
  background: theme
  environment: {}
  profile: default-(powershell)
  useConPTY: false
  autoOpen: true
hotkeys:
  shell: {}
  profile: {}
serial: {}
ssh: {}
appearance:
  vibrancy: false
  vibrancyType: fluent
  opacity: 1
  frame: native
  dock: 'off'
  css: ''
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - ssh
  - serial
enableAutomaticUpdates: false
